### ISSUE TITLE
Enemy Art

### ISSUE THREAD

**Issue by blake6993** [UoSGamesGroups/first-semester-l4-5-group-9#17]
This is the art work for the enemies. Multiple iterations are encouraged so the group can decide which ones we would like to include in the game. The enemies will most likely be known as "Memory Wipers", which may help influence their design.

Time Given: 2 Hrs

**Comment by Ochuko97** [comment]
I have created three concept designs for our game enemies. 
Time spent: 1hr

**Comment by Ochuko97** [comment]
Created basic movement sprites for desired enemy design. 
Time spent: 1hr
