### ISSUE TITLE
Shooting Animation for Player

### ISSUE THREAD

**Issue by blake6993** [UoSGamesGroups/first-semester-l4-5-group-9#18]
The animation that will trigger when the player fires at enemies. This should include some sort of shooting pose for each direction and anything else you can think of that should be included.

Time Given: 1hr/30m
Word done by: 9:00pm, 09/11/16

**Comment by Ochuko97** [comment]
Time given : 1hr/30m

**Comment by Ochuko97** [comment]
Created shooting animation sprite for player character. 
Time taken: 1 hr
