### ISSUE TITLE
Create power up instruction screen

### ISSUE THREAD

**Issue by Ochuko97** [UoSGamesGroups/first-semester-l4-5-group-9#28]
Your task is to create an instruction screen describing to the players the power of our in game pick ups. The pick ups are, health, weapon upgrade and speed boost. The instruction screen most follow the same aesthetic templates as the title screen and level select screen that were previously create. It is advised that you also uploaded the psd file as well as the png file for convenience if other members want to edit the screen. 

Time given : 2hr 
Word done by: 9:00pm, 09/11/16

**Comment by blake6993** [comment]
The instruction screen for the pickups has been completed and awaiting the official pickup art to be included.

Time spent: 1 Hr
