### ISSUE TITLE
Research into sounds that fit the motif of our game

### ISSUE THREAD

**Issue by Ochuko97** [UoSGamesGroups/first-semester-l4-5-group-9#29]
Using loyalty sound websites like Freesound.org your task is to research into sound clips and music we may implement into our game. You should compile these effects into their own folder on Github alongside a reference list using the Harvard referencing guide of their source.
The sounds are: 

- Background music for our game 

- Walking/movement sound effects for our player and enemies 

- Shooting sound effects for players and enemies  

Time given: 2hr 
Word done by: 9:00pm, 09/11/16

**Comment by blake6993** [comment]
I have found sounds that we could use in our game. I have included my references and I chose multiple sounds, to give us plenty of choices.

Time spent: 1 Hr
