### ISSUE TITLE
Implement level background art into the level select screen

### ISSUE THREAD

**Issue by Ochuko97** [UoSGamesGroups/first-semester-l4-5-group-9#30]
Dependent on the "Background level" task assigned to Bailey. Your task is to implement the art  given by Bailey to its designated Polaroid placeholder in our level select screen. 

Time given : 1hr  
Word done by: 9:00pm, 09/11/16

**Comment by blake6993** [comment]
I have incorporated the background image into the level select screen in two ways, a revealed version - after completing a level - and a hidden version - with the background barely visible.

Time spent: 30m
