### ISSUE TITLE
Create pick up art

### ISSUE THREAD

**Issue by Ochuko97** [UoSGamesGroups/first-semester-l4-5-group-9#32]
One of the mechanics featured in our game will be the players ability to utilize pick/power ups. Your task is to research into and create some concepts for the following power ups; **health, weapon upgrade and speed boost** . Once finished with the concepts you must then create the art using photoshop/sai and upload the finish assets to Github in a png and psd file format.

Time given : 2hr 
Word done by: 9:00pm, 09/11/16

**Comment by baileykeeble** [comment]
Finished the art for the three pickups, took longer than the 2 hours assigned, roughly around 3-4 hours in total.
