### ISSUE TITLE
Fog of war code

### ISSUE THREAD

**Issue by blake6993** [UoSGamesGroups/first-semester-l4-5-group-9#40]
Research and implement the fog of war into the new prototype, using the methods discussed, e.g. calling objects

Time: 1 hour
Close date: 16/11/16

**Comment by blake6993** [comment]
After looking at the repository and after seeing emails, this appears to have been completed. If this is the case, please move the task to verify and comment with the amount of time spent.

**Comment by SM1305** [comment]
Completed. 30 minutes spent on task.
