### ISSUE TITLE
Make Crystal Transparent

### ISSUE THREAD

**Issue by blake6993** [UoSGamesGroups/first-semester-l4-5-group-9#42]
Edit the final design of the crystal to include a transparent background. This task needs to be completed before the "Replace Health Pickup" task.

Time: 30 minutes
Close date: 11/11/16

**Comment by baileykeeble** [comment]
Made the crystal transparent so it can replace the one that I already uploaded but didn't make transparent.
Took roughly 10 minutes to do.
