### ISSUE TITLE
Mouse Shooting

### ISSUE THREAD

**Issue by blake6993** [UoSGamesGroups/first-semester-l4-5-group-9#47]
Implement the shooting code that's tied to the rotation of the mouse and the click of the left mouse button.

Time: 2 hours
Close date: 16/11/16

**Comment by blake6993** [comment]
After looking at the repository and after seeing emails, this appears to have been completed. If this is the case, please move the task to verify and comment with the amount of time spent.

**Comment by SM1305** [comment]
Completed. 6 hours spent on achieving functional code. 90 minutes spent on research.
