### ISSUE TITLE
Fog of war designs

### ISSUE THREAD

**Issue by blake6993** [UoSGamesGroups/first-semester-l4-5-group-9#49]
Make 4 designs for the fog of war, with each design having a slightly bigger clear space in the center.

Time: 1 hour 30 minutes
Close date: 16/11/16

**Comment by baileykeeble** [comment]
Finished doing the designs and did one extra just in case it was needed, took around 30 minutes to do in total.

**Comment by baileykeeble** [comment]
Finished the Fog of war design for the game, took around an hour in total, including the time taken beforehand.
