### ISSUE TITLE
Cursor/Crosshair design

### ISSUE THREAD

**Issue by blake6993** [UoSGamesGroups/first-semester-l4-5-group-9#50]
Produce multiple design for a cursor or crosshair that can be used in the game, to tell the player where they are aiming.

Time: 1 hour 30 minutes
Close date: 16/11/16

**Comment by blake6993** [comment]
I have seen the crosshairs that have been uploaded but I can't call the task done as the time you spent on the task hasn't been given.

**Comment by baileykeeble** [comment]
The cross hair design took roughly an hour to do in total.
