### ISSUE TITLE
Projectile design

### ISSUE THREAD

**Issue by blake6993** [UoSGamesGroups/first-semester-l4-5-group-9#51]
Produce multiple designs for the projectiles that the player/enemies will fire.

Time: 2 hours
Close date: 16/11/16

**Comment by blake6993** [comment]
I have seen the projectiles that have been uploaded but I can't call the task done as the time you spent on the task hasn't been given.

**Comment by baileykeeble** [comment]
The projectile design took around one and a half hours in total.
