### ISSUE TITLE
Create level designs for first two levels. 

### ISSUE THREAD

**Issue by Ochuko97** [UoSGamesGroups/first-semester-l4-5-group-9#57]
As we spoke in our meeting, your task is to to design the map layouts of our first two levels. These maps will be similar to the type of maps we were task with designing in our level design module. The maps must consist of the placement of enemy spawners, pickups and memory shards. 

Time given: 2hr (1hr for each map) 
Close time: 12:00am, 22/11/16

**Comment by blake6993** [comment]
- 2 designs uploaded
- Text file with notes on each design

Time spent: 1h 30m

**Comment by blake6993** [comment]
-Pickups added: 5m

**Comment by blake6993** [comment]
- 2 designs uploaded (garden and street)
- Text file with notes on each design
Time spent: 1h 30m
