### ISSUE TITLE
Create graphics for main menu buttons

### ISSUE THREAD

**Issue by Ochuko97** [UoSGamesGroups/first-semester-l4-5-group-9#60]
Your task is to create the graphic for the buttons featured in our main menu screen, these buttons consist of a 'Play', 'Instructions' and 'Quit' button. It is advised that you apply the skills, theories and techniques you have been learnt about in your intro to design methods. 

Time given: 1hr 30min 
Close time: 12:00am, 22/11/16

**Comment by baileykeeble** [comment]
Took the allotted time of an hour and thirty minutes to do, did go a little over but only by around ten minutes.
