### ISSUE TITLE
Create graphic for instruction screen

### ISSUE THREAD

**Issue by Ochuko97** [UoSGamesGroups/first-semester-l4-5-group-9#62]
Your task is to create the graphic for our instruction screen. It is advised that you use the conventions of our previous title screen created by Blake as reference for creating this current version. It is also advised that you follow the forms and conventions of, composition, colour and fonts you had studied about in your design methods lectures. 

Time given: 1 hr 
Close time: 12:00am, 22/11/16

**Comment by baileykeeble** [comment]
Took around 30mins to do.
