### ISSUE TITLE
Create background art for tutorial level.

### ISSUE THREAD

**Issue by Ochuko97** [UoSGamesGroups/first-semester-l4-5-group-9#67]
Your task is the use the resolution available in the current build of the game to create background art for the tutorial level. The tutorial levels consist of a top down view of our MC's bedroom and hallway/house. 

Time given: 1 hour 30Min 
Close time: 12:00am 23/11/16

**Comment by blake6993** [comment]
- 2 backgrounds uploaded for tutorial level
- room and hallway

Time Spent: 1h 30m
