### ISSUE TITLE
Enemies

### ISSUE THREAD

**Issue by blake6993** [UoSGamesGroups/first-semester-l4-5-group-9#71]
Your task for this week is to code and create the behaviour of the second enemy class as discussed in our meeting. 

Time: 2 Hours 
Close time: 12:00am, 07/12/16

**Comment by SM1305** [comment]
3hours spent rewriting code and bug fixing to allow intended interaction between enemies, pickups, the environment and the player.

0.5hours spent on scripting new enemy behaviour. Complete, but will aim to include further features before deadline.
