### ISSUE TITLE
Write the instructions

### ISSUE THREAD

**Issue by blake6993** [UoSGamesGroups/first-semester-l4-5-group-9#72]
After creating the instruction screen, please write the instructions on the screen. Influence can be taken from the previous screen that Blake created.

Time: 1 Hour

**Comment by baileykeeble** [comment]
I finished the task within 20-30 minutes including the time it took me to find a font that I liked for the title, however it may need to be redone as the entire thing looks to pix-elated when zooming in.

**Comment by blake6993** [comment]
I've looked at the work submitted for this and I have to reopen the issue for a couple of reasons:
- The instructions are a little brief, which could lead to some confusion for the player
- WASD should really be capitalised, so the player can easily find the controls
- There's no mention of the speed pickup. Health and the crystals have been combined, as memory now works as the primary indication of the amount of hits a player can take

I hope this helps

**Comment by blake6993** [comment]
Unfortunately I have to put this back into in progress due to there still being a mention of the health pickup. We aren't including a health pickup anymore so this needs to be removed please.
Also could you please log any extra time spent on the task.

**Comment by baileykeeble** [comment]
Updated the instructions again with what was requested, took an extra 5-10 minutes to do.
