### ISSUE TITLE
New levels

### ISSUE THREAD

**Issue by blake6993** [UoSGamesGroups/first-semester-l4-5-group-9#77]
Create 2 new levels in unity based on the level designs completed by Blake.

Time: 1 Hour 30 minutes

**Comment by Ochuko97** [comment]
Began work on new levels. 
Time taken: 30 mins

**Comment by Ochuko97** [comment]
Finished creating first level. 

Time taken: 30min

**Comment by Ochuko97** [comment]
Finished creating second level. 

Time taken: 3omins
