### ISSUE TITLE
Incorporate a checkpoint feature in our game.

### ISSUE THREAD

**Issue by Ochuko97** [UoSGamesGroups/first-semester-l4-5-group-9#83]
As it currently stands our game does have store any savepoint/checkpoints incorporated into the gameplay. Your task for this week will be to code a checkpoint into each levels allowing players to chose to 'Restart' or 'Quit' the level once deleted. 

Time: 1 hour 30 minutes 
Close time: 12:00am, 07/12/16

**Comment by SM1305** [comment]
2hours spent researching and implementing feature.
