### ISSUE TITLE
Incorporate movable borders into existing levels.

### ISSUE THREAD

**Issue by Ochuko97** [UoSGamesGroups/first-semester-l4-5-group-9#84]
As discussed in this weeks sprint, your task is incorporate the movable platforms/borders you discovered into pre-existing levels. As they are four pre-existing levels try and find a way to make the puzzles/placement of orders for difficult as the game progresses. 

Time: 2 hours 
Close time: 12:00am, 07/12/16

**Comment by SM1305** [comment]
1.5hours spent on implementing task.
